### ISSUE TITLE
NOT operation for XMILE logicals test has wrong definition

### ISSUE THREAD

**Issue by alexprey** [SDXorg/test-models#40]
The model file:
https://github.com/SDXorg/test-models/blob/master/tests/logicals/test_logicals.xmile

This model file has wrong definition at line 33

    <eqn>( IF false_input not  THEN 1 ELSE 0 )</eqn>

Should be

    <eqn>( IF not false_input THEN 1 ELSE 0 )</eqn>

------
Regards,
Alexey from sdCloud.io development team.

**Comment by JamesPHoughton** [comment]
Looks like this had been correct in [an earlier commit](https://github.com/SDXorg/test-models/blob/4d8006c6539411b094a268c41f01ebce8437cd53/tests/logicals/test_logicals.xmile) and was overwritten with the xmutil test generations. 

@wasbridge - looks like `:not:` parsing in xmutil is broken. 

I'm going to approve the PR, to bring the test to where it should be.

**Comment by JamesPHoughton** [comment]
Thanks @alexprey for a good catch. =)

**Comment by wasbridge** [comment]
Yup -- let me bring this bug back upstream in XMUtil
